name: Deploy Staging

on:
  pull_request:
    types: 
      [synchronize, opened]
    branches:
      - main

jobs:
  deploy-staging-service:
    environment: staging
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: service
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: c-hive/gha-npm-cache@v1
      - name: Install Serverless Globally
        run: npm install -g serverless
      - name: Install Dependencies
        run: npm install
      - name: Run tests
        run: npm run test
      - name: Configure AWS Staging Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}
          aws-region: us-west-2
      - name: Serverless Deploy
        run: serverless deploy --stage stage --verbose

  deploy-staging-web:
    environment: web
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: c-hive/gha-npm-cache@v1
      - name: Install Dependencies
      - name: Build app
        run: npm run build
      - name: Deploy App
        run: npm run deploy