name: Release npm Package
on:
  push:
    branches:
      - main
        
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
        env:
          NPM_REGISTRY_URL: https://registry.npmjs.org
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Use npm cache
        uses: c-hive/gha-npm-cache@v1
      - name: Install dependencies
        run: npm ci
      # These tests are flaky, so we'll want to try many times if they fail
      - name: Run tests repeatedly
        uses: nick-invision/retry@v2
        with:
          # 10 is too much but it's a required param for this action
          timeout_minutes: 10
          max_attempts: 10 
          retry_on: error
          command: npm run test
      - name: Publish to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}