name: Yarn tests on PR open

# Triggers on a Pull Request being opened or commits being added to an opened PR
on:
  pull_request:
    types: [synchronize, opened]

env:
  SOME_ENV_VAR: some_env_var_value

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Get yarn cache directory path
        id: yarn-cache-dir
        run: echo "::set-output name=cache::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir.outputs.cache }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn
      - run: yarn test
